### ISSUE TITLE
Make a "Last Release" column available to views that use the cascade plugin

### ISSUE THREAD

**Issue by jjongsma** [barchart/barchart-jenkins-cascade-plugin#27]
The maven release plugin has a "last release" column available for project views. It would be helpful to either 1) have cascade releases properly populate that field (preferred), or 2) add a similar field for last cascade release.

Rationale: when you cascade release something with 10 dependencies in a project of 50 modules, it's nice to have a quick way of knowing at a glance which modules were just released to avoid re-releasing them after the cascade completes.

**Comment by Andrei-Pozolotin** [comment]
please test now
